name: Pull Request Check

on:
  pull_request:
    paths:
      - "challenges/**"
  workflow_dispatch:

jobs:
  action-generate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate action files
        run: |
          python3 scripts/gen_action.py -a -s || exit 1

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "ci: generate action file"
          add: ".github/workflows/*"
